version: "3.9"

services:
  front-end:
    build: ./front-microservice
    ports:
      - "3000:3000"
    depends_on:
      - catalog

  catalog:
    build: ./catalog-microservice
    ports:
      - "3001:3001"

  order:
    build: ./order-microservice
    ports:
      - "3002:3002"
    depends_on:
      - catalog

networks:
  my-network:
    driver: bridge
