version: "3.8"

services:
  front-tier:
    build: ./front-microservice
    image: front-tier
    ports:
      - "3000:3000"

  catalog:
    build: ./catalog-microservice
    image: catalog
    ports:
      - "3001:3001"

  order:
    build: ./order-microservice
    image: order
    ports:
      - "3002:3002"
